[package]
name = "sqlx-paginated"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true

[features]
tracing = ["tracing/default"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]
mysql = ["sqlx/mysql"] # Planned - Q3 2026
default = ["postgres"]

[lib]
path = "src/lib.rs"

[dependencies]
sqlx-paginated-derive = { path = "../sqlx-paginated-derive", version = "0.6.0" }
sqlx = { version = "0.9.0", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "sqlite",
    "uuid",
    "chrono",
    "json"
] }
chrono = { version = "^0.4", features = ["serde"] }
tracing = { version = "^0.1", default-features = false }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = "^1.52"


[dev-dependencies]
anyhow = "^1.0"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
testcontainers = "^0.27"
testcontainers-modules = { version = "^0.15", features = ["postgres"] }
